# Generated by Django 6.0.4 on 2026-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitelista', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefas',
            new_name='Tarefa',
        ),
    ]
