# Generated by Django 6.0.4 on 2026-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelista', '0002_rename_tarefas_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(verbose_name='Concluído'),
        ),
    ]
