# Generated by Django 6.0.4 on 2026-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(upload_to='posts')),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
